version: '3'

includes:
  bp: taskfile/buildpack.Taskfile.yml
  app: taskfile/app.Taskfile.yml

vars:
  BUILD_IMAGE: taha/wolfi-build-image:latest
  RUN_IMAGE: taha/wolfi-run-image:latest
  BUILDER_NAME: taha/wolfi-fips-builder:latest
  BUILDER_CONFIG: 2-builder/builder.toml

tasks:
  default:
    cmds:
      - task: all

  all:
    desc: Build everything from scratch
    cmds:
      - task: build-img
      - task: run-img
      - task: bp:package
      - task: builder

  build-img:
    desc: Build the Wolfi Build Image
    dir: build-image
    cmds:
      - docker build -t {{.BUILD_IMAGE}} .

  run-img:
    desc: Build the Wolfi Run Image (Distroless)
    dir: run-image
    cmds:
      - docker build -t {{.RUN_IMAGE}} .
  run-img-with-shell:
    desc: Build the Wolfi Run Image (with shell for debugging)
    dir: run-image
    cmds:
      - docker build -t {{.RUN_IMAGE}}-shell -f Dockerfile.run .
  builder:
    desc: Create the final Cloud Native Builder
    cmds:
      - pack builder create {{.BUILDER_NAME}} --config {{.BUILDER_CONFIG}}

  inspect:
    desc: Inspect the final builder
    cmds:
      - pack builder inspect {{.BUILDER_NAME}}

  app-maven:
    desc: Build the sample Maven app using our custom builder
    cmds:
      - pack build taha/maven-fips-app --path 3-sample-app --builder {{.BUILDER_NAME}} --env BP_JVM_TYPE=JRE